### ISSUE TITLE
Artists with lowercase first letter pushed to bottom of list

### ISSUE THREAD

**Issue by bubblesnout** [deluan/navidrome#206] opened 2020-04-24 04:00 UTC
Hopefully a simple one, I have a few artists that are tagged in all lowercase as that's how they generally stylise their name (eg. blink-182, far, sleepmakeswaves) and currently these are all listed at the end after "Z". It would be great if the sorting wasn't case-sensitive.

**Comment by deluan** [comment] 2020-04-24 12:22
This is being taken care in #174. I'm closing this in favour of that one. Please subscribe to #174

**Closed by deluan** 2020-04-24 12:22 UTC

**Comment by deluan** [comment] 2020-04-24 16:46
This is also a duplicate of https://github.com/deluan/navidrome/issues/157
