### ISSUE TITLE
High memory usage 

### ISSUE THREAD

**Issue by Nelyah** [deluan/navidrome#684] opened 2020-12-08 08:34 UTC
As the title says, I'm experiencing a high memory usage on my server running navidrome. I am running the `latest` docker image (updated a few days ago), on a ~100GB library. 

I stumbled onto this reddit discussion: https://www.reddit.com/r/navidrome/comments/jz3gsc/severe_memory_and_cpu_usage/ 
but it looks like the cause of that memory usage should have been disabled in the latest release `0.39.0`. I am also _not_ seeing any unusual CPU activity. 

The memory used by the `/app/navidrome` process (running inside docker) got to more than 5GB after 3-4 days. I down/up the docker yesterday night (to reset the memory consumption) and it gained ~600MB memory usage over night. 

I am unsure if this is something I can help fixing, or if there's any more metric which could help?

**Comment by SteveDinn** [comment] 2020-12-08 14:18
I've noticed this as well. No extra CPU usage, but dramatically higher memory usage. I'm also using the `deluan/navidrome` docker image.

**Comment by Nelyah** [comment] 2020-12-08 14:46
> Edit: Confirmed. I watched the process in htop as I clicked the 'Random' link a few times and watched the memory grow and grow.

I've noticed that as well, though unless I'm mistaken the latest release disables the Image cache? Maybe that isn't the reason for it? 

I also saw a rise of ~5-8MB each time I would click "Random", but the memory _does_ go up without me doing that (when the instance is simply left as is with no user listening)

**Comment by deluan** [comment] 2020-12-08 15:45
Thanks for the report. Do you see anything unusual in the logs (any error or warning?) Does the growing memory usage slows down if you reduce the ScanInterval (default every minute)?

> Edit: Confirmed. I watched the process in htop as I clicked the 'Random' link a few times and watched the memory grow and grow.

Does it happen only in "Random", not in other Album Views? I'll take a look, but this can be just SQLite loading new data from the DB and keeping it in its internal cache. This could also be caused by the image processing functions, creating big cluster of objects that will eventually be recollected by the GC. In this case it is normal behaviour and the memory used eventually down

> I stumbled onto this reddit discussion: https://www.reddit.com/r/navidrome/comments/jz3gsc/severe_memory_and_cpu_usage/ but it looks like the cause of that memory usage should have been disabled in the latest release `0.39.0`

The issue in that discussion was related to the Web UI, not the server, and it was fixed (not disabled) in 0.39.0 (just for the record, in case someone reads this 😄)

**Comment by Nelyah** [comment] 2020-12-08 16:49
> reduce the ScanInterval

I can try that, then monitor how the memory usage grows. I'll try to run it overnight and see how it fares

> Does it happen only in "Random", not in other Album Views?

The first time I clicked "Recently played" and "recently added" I got a bump of ~50MB in RAM in each case. But subsequent clicks don't change memory usage. In the album view (meaning when I click on an album and get its list of songs, right?) I didn't notice any augmentation in memory usage. 

> Do you see anything unusual in the logs

I do! Shame on me for not checking that first :(

Those are the 4 "types" of error I saw in my log. Looking at it, it _might_ be an issue on my end, I'm unsure. It looks like it's getting a 503 for `http://navidrome.mydomain.com`. In my case, I have a nginx reverse proxy, so requests to this address should redirect to https, then nginx will forward it to navidrome. The error `Error retrieving coverArt` seem to send to `172.30.0.2` which is the local address for the navidrome container... So it seems my nginx forwarding isn't the problem here? I'm unsure

```
time="2020-12-08T16:26:44Z" level=error msg="HTTP: GET http://navidrome.mydomain.com/rest/getCoverArt?u=my_username&t=9ecfe0437d8cd8d3c61ed0d9c9416023&s=917f2a&f=json&v=1.8.0&c=NavidromeUI&id=5ef40649930b1bedf7c8fff5243ef416&size=300" elapsedTime=125.193561ms httpStatus=503 remoteAddr=192.168.1.254 requestId=c46541390b8d/r0HlSBCvBy-091204 responseSize=22
time="2020-12-08T16:26:44Z" level=error msg="Error retrieving coverArt" error="write tcp 172.30.0.2:80->172.30.0.3:34604: write: broken pipe" id=d09276fe393975468631fa825b71eaeb requestId=c46541390b8d/r0HlSBCvBy-091202
time="2020-12-08T16:26:44Z" level=warning msg="API: Failed response" error=0 message="Internal Error" requestId=c46541390b8d/r0HlSBCvBy-091202
time="2020-12-08T16:26:44Z" level=error msg="Error sending response to client" error="write tcp 172.30.0.2:80->172.30.0.3:34604: write: broken pipe" payload="{\"subsonic-response\":{\"status\":\"fail\",\"version\":\"1.16.1\",\"type\":\"navidrome\",\"serverVersion\":\"0.39.0 (f2a8308)\",\"error\":{\"code\":0,\"message\":\"Internal Error\"}}}" requestId=c46541390b8d/r0HlSBCvBy-091202
```

> The issue in that discussion was related to the Web UI, not the server, and it was fixed (not disabled)

Woops. Thanks for the clarification :smile:

**Comment by SteveDinn** [comment] 2020-12-08 17:09
I'm getting these errors approximately once per minute:
```
time="2020-12-08T16:59:17Z" level=warning msg="Pre-cache warmer is not available as ImageCache is DISABLED"
time="2020-12-08T17:00:16Z" level=warning msg="Pre-cache warmer is not available as ImageCache is DISABLED"
time="2020-12-08T17:01:16Z" level=warning msg="Pre-cache warmer is not available as ImageCache is DISABLED"
time="2020-12-08T17:02:16Z" level=warning msg="Pre-cache warmer is not available as ImageCache is DISABLED"
time="2020-12-08T17:03:16Z" level=warning msg="Pre-cache warmer is not available as ImageCache is DISABLED"
time="2020-12-08T17:04:17Z" level=warning msg="Pre-cache warmer is not available as ImageCache is DISABLED"
time="2020-12-08T17:05:16Z" level=warning msg="Pre-cache warmer is not available as ImageCache is DISABLED"
```

**Comment by BobWs** [comment] 2020-12-09 07:21
> > reduce the ScanInterval
> 
> I can try that, then monitor how the memory usage grows. I'll try to run it overnight and see how it fares
> 
> > Does it happen only in "Random", not in other Album Views?
> 
> The first time I clicked "Recently played" and "recently added" I got a bump of ~50MB in RAM in each case. But subsequent clicks don't change memory usage. In the album view (meaning when I click on an album and get its list of songs, right?) I didn't notice any augmentation in memory usage.
> 
> > Do you see anything unusual in the logs
> 
> I do! Shame on me for not checking that first :(
> 
> Those are the 4 "types" of error I saw in my log. Looking at it, it _might_ be an issue on my end, I'm unsure. It looks like it's getting a 503 for `http://navidrome.mydomain.com`. In my case, I have a nginx reverse proxy, so requests to this address should redirect to https, then nginx will forward it to navidrome. The error `Error retrieving coverArt` seem to send to `172.30.0.2` which is the local address for the navidrome container... So it seems my nginx forwarding isn't the problem here? I'm unsure
> 
> ```
> time="2020-12-08T16:26:44Z" level=error msg="HTTP: GET http://navidrome.mydomain.com/rest/getCoverArt?u=my_username&t=9ecfe0437d8cd8d3c61ed0d9c9416023&s=917f2a&f=json&v=1.8.0&c=NavidromeUI&id=5ef40649930b1bedf7c8fff5243ef416&size=300" elapsedTime=125.193561ms httpStatus=503 remoteAddr=192.168.1.254 requestId=c46541390b8d/r0HlSBCvBy-091204 responseSize=22
> time="2020-12-08T16:26:44Z" level=error msg="Error retrieving coverArt" error="write tcp 172.30.0.2:80->172.30.0.3:34604: write: broken pipe" id=d09276fe393975468631fa825b71eaeb requestId=c46541390b8d/r0HlSBCvBy-091202
> time="2020-12-08T16:26:44Z" level=warning msg="API: Failed response" error=0 message="Internal Error" requestId=c46541390b8d/r0HlSBCvBy-091202
> time="2020-12-08T16:26:44Z" level=error msg="Error sending response to client" error="write tcp 172.30.0.2:80->172.30.0.3:34604: write: broken pipe" payload="{\"subsonic-response\":{\"status\":\"fail\",\"version\":\"1.16.1\",\"type\":\"navidrome\",\"serverVersion\":\"0.39.0 (f2a8308)\",\"error\":{\"code\":0,\"message\":\"Internal Error\"}}}" requestId=c46541390b8d/r0HlSBCvBy-091202
> ```
> 
> > The issue in that discussion was related to the Web UI, not the server, and it was fixed (not disabled)
> 
> Woops. Thanks for the clarification 😄
> 
> Edit:
> 
> forgot to add:
> 
> > In this case it is normal behaviour and the memory used eventually down
> 
> I thought of something like that, but it looks like the memory isn't going down much, and eventually reached yesterday 70% of my server RAM (which triggered some swapping and slowed things down).

Having the same error message also using reverse proxy. But I have been using reverse proxy since day one and never had these errors before, it happened since version 0.37

**Comment by BobWs** [comment] 2020-12-09 07:22
> I'm getting these errors approximately once per minute:
> 
> ```
> time="2020-12-08T16:59:17Z" level=warning msg="Pre-cache warmer is not available as ImageCache is DISABLED"
> time="2020-12-08T17:00:16Z" level=warning msg="Pre-cache warmer is not available as ImageCache is DISABLED"
> time="2020-12-08T17:01:16Z" level=warning msg="Pre-cache warmer is not available as ImageCache is DISABLED"
> time="2020-12-08T17:02:16Z" level=warning msg="Pre-cache warmer is not available as ImageCache is DISABLED"
> time="2020-12-08T17:03:16Z" level=warning msg="Pre-cache warmer is not available as ImageCache is DISABLED"
> time="2020-12-08T17:04:17Z" level=warning msg="Pre-cache warmer is not available as ImageCache is DISABLED"
> time="2020-12-08T17:05:16Z" level=warning msg="Pre-cache warmer is not available as ImageCache is DISABLED"
> ```

Same errors and after I re-enabled the cache the error message disappeared.

**Comment by Nelyah** [comment] 2020-12-09 08:20
> reduce the ScanInterval

I started the instance before going to bed with `ND_SCANINTERVAL: "744h"` and the memory usage hasn't increased overnight :tada: 

At this point I may just disable it and manually rescan whenever I add some music to my library (which isn't _that_ often). But it might still be interesting to understand why this triggers such a high memory consumption.

---

Also, would you know if those errors I'm getting are due to some misconfiguration on my end or because of something in Navidrome?

**Comment by deluan** [comment] 2020-12-09 15:28
So it seems that the scaner has a memory leak somehow.... Can you please set LogLevel to trace, set ScanInterval to something like 744h and send me the full log from the moment Navidrome starts up until it finishes the first scan cycle (the first scan happens 5 seconds after starting Navidrome). You can send it to my email: deluan AT navidrome . org

Anyway, keeping it disabled is a better approach in general, but it would be good to track down this issue.

-----

> I'm getting these errors approximately once per minute:
> 
> ```
> time="2020-12-08T16:59:17Z" level=warning msg="Pre-cache warmer is not available as ImageCache is DISABLED"
> time="2020-12-08T17:00:16Z" level=warning msg="Pre-cache warmer is not available as ImageCache is DISABLED"
> ```

These are caused by an error in the logging (they should not appear if the ImageCache is manually disabled). It is already fixed in master, and will be fixed in the next release

----

> time="2020-12-08T16:26:44Z" level=error msg="HTTP: GET http://navidrome.mydomain.com/rest/getCoverArt?u=my_username&t=9ecfe0437d8cd8d3c61ed0d9c9416023&s=917f2a&f=json&v=1.8.0&c=NavidromeUI&id=5ef40649930b1bedf7c8fff5243ef416&size=300" elapsedTime=125.193561ms httpStatus=503 remoteAddr=192.168.1.254 requestId=c46541390b8d/r0HlSBCvBy-091204 responseSize=22
> time="2020-12-08T16:26:44Z" level=error msg="Error retrieving coverArt" error="write tcp 172.30.0.2:80->172.30.0.3:34604: write: broken pipe" id=d09276fe393975468631fa825b71eaeb requestId=c46541390b8d/r0HlSBCvBy-091202
> time="2020-12-08T16:26:44Z" level=warning msg="API: Failed response" error=0 message="Internal Error" requestId=c46541390b8d/r0HlSBCvBy-091202
> time="2020-12-08T16:26:44Z" level=error msg="Error sending response to client" error="write tcp 172.30.0.2:80->172.30.0.3:34604: write: broken pipe" payload="{\"subsonic-response\":{\"status\":\"fail\",\"version\":\"1.16.1\",\"type\":\"navidrome\",\"serverVersion\":\"0.39.0 (f2a8308)\",\"error\":{\"code\":0,\"message\":\"Internal Error\"}}}" requestId=c46541390b8d/r0HlSBCvBy-091202

> Having the same error message also using reverse proxy. But I have been using reverse proxy since day one and never had these errors before, it happened since version 0.37

I'll take a look at these, although I don't think they are the causing any memory leak

**Comment by deluan** [comment] 2020-12-09 19:24
Hey @Nelyah , I received the logs, and I see there's a lot of reconnections from the Activity Panel, and it keeps up to 8 connections simultaneously (how many instances of the UI did you have open?). As the logs shows that it should be disabled (`DevActivityPanel: false`), maybe you didn't refresh the UI? Check if the version in the UI matches the server version (`0.39.0 (f2a8308)`)

It also shows that the last scanned folder is `/music/Pictures at ....`. They are scanned alphabetically, don't you have anything after this one?

**Comment by Nelyah** [comment] 2020-12-09 19:50
> it keeps up to 8 connections simultaneously (how many instances of the UI did you have open?)

Sorry about that. I'm also sharing the server with some friends and can't really control how many instance they have. I have quite a few computers myself (each had a Navidrome instance) so the number doesn't seem out of place to me. 

> maybe you didn't refresh the UI

I've checked the UI (upper right menu, then "About"), it shows the version `0.39.0 (f2a8308)` which seems to match. 

> It also shows that the last scanned folder is /music/Pictures at ....

I've down/up my container again to check. It's now been running for ~15 and it found only 122 entries in less than 2s and stopped at `/music/Harpsichord Recital [80]`. Then it hasn't found anything else for the past 15min.

I've then tried to run (in the folder where the navidrome docker-compose file is) `docker-compose exec navidrome scan -f | grep -ic "found directory"`: I get 447 lines (which probably amounts to the number of entries)

**Comment by deluan** [comment] 2020-12-09 21:18
If all users have the latest version, I don't know why your server is getting requests for the http://navidrome.mydomain.com/app/api/events endpoint. I did a change to disable dis endpoint if the activity panel is disabled. Can you try the latest `develop` build (`deluan/navidrome:develop`), and send me the logs again? My suspicion is that the `/events` requests are causing issues in your installation

**Comment by Nelyah** [comment] 2020-12-10 09:45
I haven't gotten to try the `develop` build yet, but just re- downed/up the container. Before up-ing the container, I pointedly closed the one instance I had running (which seemed to be the one doing the `/events` requests). The client I closed _did_ show the latest version of Navidrome. With that, I think _all_ clients were closed. 

This time `docker-compose logs |  grep -ic "found directory"` showed 447, as I would have expected yesterday. I'm also _not_ seeing any `/events` requests in the logs anymore.  

So I think you must be right, that one client kept going on with the old version (I don't think I had closed any of them when I got the leak), even though they were all showing the correct one. Then, maybe with the client running an older version underneath pinging the new Navidrome instance it was causing a leak? I'm just kind of wild guessing here. 

In any case, I think the issue seems to be solved in my case. Let me know if you still want me to try out the `develop` version (but I'm not getting any more `/events` so...). Thanks a lot for the help and bearing with me in debugging this!

**Comment by deluan** [comment] 2020-12-10 16:39
Yeah, I was able to reproduce this behaviour here. There's some race condition in the events endpoint when doing a scan. Can you do one more test? Set the `ScanInterval="1m"`, and measure any memory increase overnight, so we can be sure that the memory leak was caused by this race condition.

**Comment by Nelyah** [comment] 2020-12-10 16:42
Will do! And post what I find tomorrow. Should I test that on `develop` or `latest`?

**Comment by deluan** [comment] 2020-12-10 16:48
Please test with the `develop` build

**Comment by Nelyah** [comment] 2020-12-11 10:47
So, I got data only until 5AM (after which the container got restarted because there was a new `develop` available). However, it doesn't look like there was any memory leak. It looks like it plateaued at ~110MB from the moment I went to bed to 5AM. :tada: 

Thanks a lot for the fix! :smile:

**Comment by deluan** [comment] 2020-12-12 23:52
Hey @Nelyah , can you please test the latest `develop` build? Please enable the activity panel (`ND_DEVACTIVITYPANEL=true`) and also enable scan with a small interval (`ND_SCANINTERVAL=1m`), and please keep an open tab in the browser (make sure the activity panel is there)

Let me know if you see an increase of memory usage with this build. Thanks

**Comment by Nelyah** [comment] 2020-12-13 17:00
I've started an instance of Navidrome on the latest `develop` with the following `docker-compose.yml` (so you can refer to it to check I've enabled things correctly). 

```yaml
version: "3"
services:
  navidrome:
    image: docker.io/deluan/navidrome:develop
    restart: unless-stopped
    environment:
      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data
      user: 1000:1000
      ND_DEVACTIVITYPANEL: "true"
      ND_SCANINTERVAL: "1m"
      ND_LOGLEVEL: trace
      ND_PORT: 80
      ND_TRANSCODINGCACHESIZE: 100MB
      ND_SESSIONTIMEOUT: "744h"
      ND_BASEURL: ""
    networks:
      - navidrome
    volumes:
      - ${MUSIC_FOLDER}:/music:ro
      - navidrome_data:/data/

volumes:
  navidrome_data:
    external: true

networks:
  navidrome:
    external: true
```

I have checked and the logs tell me that `DevActivityPanel: true`, so it must be enabled. However I don't see anything different in the UI. I'm not sure what it's supposed to look like either. I'm joining a screenshot of what I currently have. I have refreshed, then closed and opened the tab again.

<img width="1920" alt="Screen Shot 2020-12-13 at 17 56 05" src="https://user-images.githubusercontent.com/6171842/102018239-7d20dc80-3d6c-11eb-9073-0a6696990a93.png">

ps: Great concerto by the way.

**Comment by deluan** [comment] 2020-12-13 17:15
Thanks for the test. When changing configs like this, you'll need to force-refresh the browser, so it reloads the latest config in the `index.html`

Can you confirm which version Navidrome reports in the initialization?

PS: Thanks for the concert tip ;)

**Comment by Nelyah** [comment] 2020-12-13 17:28
Ah, right. Indeed after clearing the cache I'm getting the same thing as Chrome (so activity panel present, but kind of buggy). 

Here's the output when I run the container, so the version is `Version: 0.39.0-SNAPSHOT (e27d917)`. 

```
  _   _             _     _
 | \ | |           (_)   | |
 |  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___
 | . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
 | |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/
 \_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|
                   Version: 0.39.0-SNAPSHOT (e27d917)

 time="2020-12-13T17:21:34Z" level=debug msg="Opening DataBase" dbPath="/data/navidrome.db?cache=shared&_busy_timeout=15000&_journal_mode=WAL&_foreign_keys=on" driver=sqlite3
 Loaded configuration from '': &conf.configOptions{
     ConfigFile:                 "",
     Address:                    "0.0.0.0",
     Port:                       80,
     MusicFolder:                "/music",
     DataFolder:                 "/data",
     DbPath:                     "/data/navidrome.db?cache=shared&_busy_timeout=15000&_journal_mode=WAL&_foreign_keys=on",
     LogLevel:                   "trace",
     ScanInterval:               60000000000,
     SessionTimeout:             2678400000000000,
     BaseURL:                    "",
     UILoginBackgroundURL:       "https://source.unsplash.com/random/1600x900?music",
     EnableTranscodingConfig:    false,
     EnableDownloads:            true,
     TranscodingCacheSize:       "100MB",
     ImageCacheSize:             "0",
     AutoImportPlaylists:        true,
     SearchFullString:           false,
     IgnoredArticles:            "The El La Los Las Le Les Os As O A",
     IndexGroups:                "A B C D E F G H I J K L M N O P Q R S T U V W X-Z(XYZ) [Unknown]([)",
     ProbeCommand:               "ffmpeg %s -f ffmetadata",
     CoverArtPriority:           "embedded, cover.*, folder.*, front.*",
     CoverJpegQuality:           75,
     UIWelcomeMessage:           "",
     EnableGravatar:             false,
     GATrackingID:               "",
     AuthRequestLimit:           5,
     AuthWindowLength:           20000000000,
     Scanner:                    conf.scannerOptions{Extractor:"taglib"},
     LastFM:                     conf.lastfmOptions{ApiKey:"", Secret:"", Language:"en"},
     Spotify:                    conf.spotifyOptions{},
     DevLogSourceLine:           false,
     DevAutoCreateAdminPassword: "",
     DevPreCacheAlbumArtwork:    false,
     DevFastAccessCoverArt:      false,
     DevOldCacheLayout:          false,
     DevActivityPanel:           true,
 }
```

**Comment by deluan** [comment] 2020-12-13 17:38
Ah, this version (e27d917) is still buggy.... Can you try the latest latest :)?

**Comment by Nelyah** [comment] 2020-12-13 18:13
Updated to `Version: 0.39.0-SNAPSHOT (1d33841)` 😄 

```
 _   _             _     _
| \ | |           (_)   | |
|  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___
| . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
| |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/
\_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|
                  Version: 0.39.0-SNAPSHOT (1d33841)
time="2020-12-13T17:59:46Z" level=debug msg="Opening DataBase" dbPath="/data/navidrome.db?cache=shared&_busy_timeout=15000&_journal_mode=WAL&_foreign_keys=on" driver=sqlite3
Loaded configuration from '': &conf.configOptions{
    ConfigFile:                 "",
    Address:                    "0.0.0.0",
    Port:                       80,
    MusicFolder:                "/music",
    DataFolder:                 "/data",
    DbPath:                     "/data/navidrome.db?cache=shared&_busy_timeout=15000&_journal_mode=WAL&_foreign_keys=on",
    LogLevel:                   "trace",
    ScanInterval:               60000000000,
    SessionTimeout:             2678400000000000,
    BaseURL:                    "",
    UILoginBackgroundURL:       "https://source.unsplash.com/random/1600x900?music",
    EnableTranscodingConfig:    false,
    EnableDownloads:            true,
    TranscodingCacheSize:       "100MB",
    ImageCacheSize:             "0",
    AutoImportPlaylists:        true,
    SearchFullString:           false,
    IgnoredArticles:            "The El La Los Las Le Les Os As O A",
    IndexGroups:                "A B C D E F G H I J K L M N O P Q R S T U V W X-Z(XYZ) [Unknown]([)",
    ProbeCommand:               "ffmpeg %s -f ffmetadata",
    CoverArtPriority:           "embedded, cover.*, folder.*, front.*",
    CoverJpegQuality:           75,
    UIWelcomeMessage:           "",
    EnableGravatar:             false,
    GATrackingID:               "",
    AuthRequestLimit:           5,
    AuthWindowLength:           20000000000,
    Scanner:                    conf.scannerOptions{Extractor:"taglib"},
    LastFM:                     conf.lastfmOptions{ApiKey:"", Secret:"", Language:"en"},
    Spotify:                    conf.spotifyOptions{},
    DevLogSourceLine:           false,
    DevAutoCreateAdminPassword: "",
    DevPreCacheAlbumArtwork:    false,
    DevFastAccessCoverArt:      false,
    DevOldCacheLayout:          false,
    DevActivityPanel:           true,
}
```

**Comment by deluan** [comment] 2020-12-13 18:54
Great! Let me know if you experience any memory usage increase, or the "server offline" indicator (don't forget to force-refresh the browser). Thanks for helping test this

**Comment by Nelyah** [comment] 2020-12-13 20:03
Ok, so I'm noticing some funny behaviour with the activity panel:

When the `ScanInterval` triggers a scan, I can see in the log that it's finding everything. However, on the Activity Panel on the UI it sets the `Total Folders Scanned:` to a random-ish (low) number, something between 3 and 40 and sets the `Server Uptime` to `OFFLINE`. The buttons are greyed out.

If I force-refresh, the Activity panel shows 445 folders scanned (expected), but the server is `OFFLINE`, but I can click on the buttons. 
- If I click on `Quick Scan` I get the same behaviour as the one triggered by `ScanInterval`
- If I click on `Full Scan` it updates the server status and shows the correct uptime. It also scans the folders but seems to hang around ~410. 

Besides that, the memory usage seems stable.

--- 

> Thanks for helping test this

Thank _you_ for making this! :)

**Comment by deluan** [comment] 2020-12-14 03:08
There were also some race conditions in the UI. I (hopefully) fixed it all now. Can you please test with the latest develop build (version a241865)?

**Comment by Nelyah** [comment] 2020-12-14 08:32
Unfortunately I'm experiencing the same behaviour (on build `a241865`) 😞

**Comment by deluan** [comment] 2020-12-21 14:47
Fixed in latest master. Will be part of next release. Thanks @Nelyah for helping debug this.

**Closed by deluan** 2020-12-21 14:47 UTC
