### ISSUE TITLE
Issue playing mp3 files but not flac files

### ISSUE THREAD

**Issue by PBlock96** [deluan/navidrome#729] opened 2021-01-17 21:02 UTC
As discussed on discord, here is the issue brief with an example of an offending mp3 file.
Hello, I have run into an interesting problem that I can't seem to find any reference to on the github.

Setup:
Navidrome running behind a reverse proxy on nginx with ssl enabled. Running on a subdomain of my main domain used for a bunch of other stuff.
Navidrome is running on a Manjaro machine with a LEMP stack. The files are located on a separate file server (CentOS) mounted read-only with sshfs.
Currently I am working with a library that is approx. 17k songs, with most of them (16k) being flac and the remaining being mp3.
Approx 1/2 of the mp3s are transcoded versions of the FLAC files with the only difference between the two is the format and the file suffix (.mp3 instead of .flac). These files have the exact same location in the file tree.
Using the built in Navidrome web ui.

Problem:
 At this point I am able to play and scan through the FLAC songs perfectly fine, however when I try to play any of the mp3 songs nothing happens other than the player updating the album art and the track name/album. In the UI, the mp3s appear to have no duration in the web ui and when I download them from my backend they do not have any tags associated with them. However they still play as one would expect through VLC, and in addition a koel instance that I had running on this machine was able to play both the mp3 and flac versions of the songs. N.B. the other 1/2 of the mp3s have no flac pairing, but also have this problem.

[OffendingMP3s.zip](https://github.com/deluan/navidrome/files/5826834/OffendingMP3s.zip)

**Comment by deluan** [comment] 2021-02-01 01:42
Sorry for the long delay in looking into this. I checked your files and they seem to be a bit... problematic.
When extracting tags manually using both taglib and ffmpeg and I get weird results:

TagLib:
```
 $ tagreader ~/Music/Music/Media/_/Test-729/OffendingMP3s/01\ -\ Anthem\ For\ The\ Underdog.mp3
******************** "/Users/deluan/Music/Music/Media/_/Test-729/OffendingMP3s/01 - Anthem For The Underdog.mp3" ********************
-- TAG (basic) --
title   - "Anthem For The Underdog"
artist  - "12 Stones"
album   - "Anthem For The Underdog (Bonus Track Version)"
year    - "2014"
comment - ""
track   - "1"
genre   - "Rock"
-- TAG (properties) --
ALBUM       - "Anthem For The Underdog (Bonus Track Version)"
ALBUMARTIST - "12 Stones"
ARTIST      - "12 Stones"
BARCODE     - "601501313226"
BPM         - "125.3"
DATE        - "2014-24-06"
DISCNUMBER  - "1"
GENRE       - "Rock"
ISRC        - "USWU30700041"
LABEL       - "The Bicycle Music Company"
LENGTH      - "184000"
TITLE       - "Anthem For The Underdog"
TRACKNUMBER - "1"
-- AUDIO --
bitrate     - 0
sample rate - 0
channels    - 0
length      - 0:00
```
You see it read some tags but the length of the track is 0

This is ffmpeg:
```
 $ ffmpeg -i ~/Music/Music/Media/_/Test-729/OffendingMP3s/01\ -\ Anthem\ For\ The\ Underdog.mp3
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with Apple clang version 12.0.0 (clang-1200.0.32.27)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.3.1_4 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fc6b5012a00] Discarding ID3 tags because more suitable tags were found.
[aac @ 0x7fc6b4808600] channel element 3.12 is not allocated
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/deluan/Music/Music/Media/_/Test-729/OffendingMP3s/01 - Anthem For The Underdog.mp3':
  Metadata:
    major_brand     : 3gp6
    minor_version   : 0
    compatible_brands: 3gp6dby1isom
    creation_time   : 2015-07-22T02:49:55.000000Z
  Duration: 00:03:04.55, start: 0.000000, bitrate: 103 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 96 kb/s (default)
    Metadata:
      creation_time   : 2015-07-22T02:49:55.000000Z
      handler_name    : sound handler
```
No tags, and the length is correct (I think), also note that ffmpeg says the file is a `aac`  (mp4) file, not a `mp3`.....

I can play the files in VLC, but not in iTunes, nor in macOS preview. Chrome is able to display the length, but does not play the song. Seems like your files are corrupted somehow and you may get luck playing them in some players but not so much in others....


PS: By the way, you don't need the `mp3` if you just keep them for streaming. Navidrome can transcode the FLAC files to mp3 (or better yet, Opus) on the fly.

**Comment by certuna** [comment] 2021-02-01 16:59
I've got an MP3 scan/repair tool, it says: `Garbage at the end of the file. Too few MPEG frames (it's unlikely that this is a MPEG audio file).` So definitely something funky with these files.

**Comment by PBlock96** [comment] 2021-02-03 03:45
After manually editing some of the tags and setting them properly these files work. Though as a future improvement it might be nice to add in some resiliency for improper or non-existent tags. Maybe something along the lines of displaying information that can't be pulled from tags as "Unreadable" or in the case of numeric tags such as length, track num, etc. displaying dashes?

**Comment by deluan** [comment] 2021-02-03 04:04
The main issue is not that Navidrome was not reading the malformed tags, the issue is that the files are not playable in Chrome (and possible other browsers), so no Web player would be able to play them. 

You can try yourself dragging one of the fixed files to a Chrome window, so you can see they play normally. But if you drag one of the old ones, it does not play.

This is a hard situation to handle. All tags were actually read by TagLib, so Navidrome was showing it correctly. But the duration was broken, and an audio file can have a duration smaller than a second, thus I can't just replace 0 with a dash or anything, as it can be a valid length.

And this "resilience" is already in place for other tags. If ND can't read artist it shows "[Unknown Artists]", same thing for album. If the title of the song is not readable it shows the path instead.

Well, happy we were able to figure this out. I'm closing this for now, but feel free to reopen if you still have any concerns.

**Closed by deluan** 2021-02-03 04:04 UTC
