### ISSUE TITLE
OGG suport

### ISSUE THREAD

**Issue by beudbeud** [deluan/navidrome#83] opened 2020-02-24 13:36 UTC
Hi, 
I think navidrome not support ogg files. All my album on ogg are name [Unknown Album] and i can't listen it

And navidrome can't get metadata from ogg

**Comment by deluan** [comment] 2020-02-24 18:01
It should be working... I'll confirm and let you know.

**Comment by deluan** [comment] 2020-02-24 18:07
Can you send me one of your ogg files? If you can, please send it to my email (it is in my GitHub profile). Thanks.

**Comment by beudbeud** [comment] 2020-02-25 08:41
Ok i just send you files

**Comment by deluan** [comment] 2020-02-25 15:22
I got the files. Can you confirm your setup:
1) How are you running (Docker? if not, which OS?)
2) Which version are you using? 

There was a bug fixed in version 0.8.3 that would prevent getting metadata from Ogg files. Can you make sure you are using the latest version?

**Comment by beudbeud** [comment] 2020-02-25 16:49
> I got the files. Can you confirm your setup:
> 
>     1. How are you running (Docker? if not, which OS?)

Yes I use Docker image
 
>     2. Which version are you using?

 I used old version
 
> There was a bug fixed in version 0.8.3 that would prevent getting metadata from Ogg files. Can you make sure you are using the latest version?

 i updated to 0.8.3 there are no more problem about metadata but i still ca'nt listen the music.

**Comment by beudbeud** [comment] 2020-02-25 16:54
My first test was with firefox and is not reading the song but i just try on Chromium and it's work

**Comment by deluan** [comment] 2020-02-25 17:39
Cool. I'll leave this issue open to investigate why it is not playing ogg files in Firefox.

Transcoding will solve such situations, but while it is not fully ready, you can force transcoding to MP3 and it should play in any player.

To do that just set these env vars:
```
ND_ENABLEDOWNSAMPLING: "true"
ND_MAXBITRATE: 128 # can be anything less then your Ogg files bitrate
```

If you also want to experiment with Opus, configure ffmpeg to use it:
```
ND_DOWNSAMPLECOMMAND: "ffmpeg -i %s -map 0:0 -b:a %bk -v 0 -c:a libopus -f opus -"
```

**Comment by deluan** [comment] 2020-03-02 16:24
I was not able to reproduce this in the latest version of Firefox, it played Ogg files correctly. As you are not experiencing this error anymore and this will be a non-issue when transcoding is ready, I'm closing this for now

**Closed by deluan** 2020-03-02 16:24 UTC
