### ISSUE TITLE
Improvements ideas

### ISSUE THREAD

**Issue by ebanDev** [deluan/navidrome#558] opened 2020-10-10 10:43 UTC
I think it would be really cool if 
- a "delete song" button was added
- an audiobook support was added
- an "edit metadata" function was added

**Comment by ebanDev** [comment] 2020-10-10 10:44
I think it would be really cool if an audiobook support was added 👍

**Comment by deluan** [comment] 2020-10-10 14:06
Thanks for the suggestions!

> * an audiobook support was added

This is already supported by the Subsonic API. In fact Navidrome works great with Booksonic App, for example, but any client with bookmark support should work (ex: DSub). 

I plan to add bookmarking to the UI, and this is covered by #245

> * a "delete song" button was added
> * an "edit metadata" function was added

Sorry, but these are out of scope for Navidrome. It does not write to your music folder by design, to make it more secure. There are better tools out there to manage and tag you music library (beets, Picard, etc...)

**Closed by deluan** 2020-10-10 14:06 UTC

**Comment by dhruvinsh** [comment] 2020-11-07 04:05
@deluan 
Thanks for this awesome and lightweight project. 

>a "delete song" button was added
I agree that you are making sure that Navidrome is more secure by not writing anything to user directory. Your point of view is absolutely right here. 

But normally what happen is, while listening to the song, in my case, I realize that I had to delete it. And just for that purpose opening other tool is bit tedious, and always end up keep that song. And this cycle continues.

So if you provide Song deletion option that would be great! Obviously here security is main focus, so by design we can have deletion disabled by default. If someone wants to enable it then special option need to select or in case of Docker, some environment variable need to set. That way it will be user's responsibility to maintain the security and you will be off the hook.

Please consider this particular feature.
