### ISSUE TITLE
Playing from third party app doesn't update "Recently Played"

### ISSUE THREAD

**Issue by SteveDinn** [deluan/navidrome#593] opened 2020-10-23 19:14 UTC
When playing from the native Navidrome UI, the Recently Played list is updated when a song finishes playing, however, in both third-party apps I've tried ([DSub](https://github.com/daneren2005/Subsonic), and [tamland's airsonic-frontend](https://github.com/tamland/airsonic-frontend)), nothing is added to the Recently played list.

I'm on Version 0.36.0 (ed84c5a) in Docker.

**Comment by deluan** [comment] 2020-10-24 00:50
The client needs to call the [scrobble](http://www.subsonic.org/pages/api.jsp#scrobble) endpoint for the server to register the play, even if you don't use Last.FM (this is also true for Subsonic and possibly for Airsonic as well)

I checked a few Web Subsonic clients and here's whether they call `scrobble` or not:
- Jamstash: OK
- Aurial: OK
- Subplayer: NO
- tamland's airsonic-frontend: NO

For DSub (and other clients, ex: MusicStash), you need to enable the scrobble call in the "Playback" settings screen:
<img width="542" alt="Screen Shot 2020-10-23 at 8 46 22 PM" src="https://user-images.githubusercontent.com/331353/97063976-e8221400-1570-11eb-972a-bd3de2329351.png">

Currently Navidrome uses this only to register the play, and does not send the scrobble to Last.FM, even if Last.FM is configured. Scrobbling to Last.FM is coming in a future release (sooner than later)

Hope this helps clarify things a bit. Please let me know if this solves your issue.

**Comment by SteveDinn** [comment] 2020-10-24 04:52
Yes, this helped with DSub, but as you said, tamland's front-end does not do scrobbling.

I always thought it should be the other way around, when you played something, the backend service (i.e., navidrome, airsonic, etc) would take care of the scrobbling for you if you wanted it to -- maybe configurable per client app. The client app shouldn't care, the service should just do it for you.

**Comment by deluan** [comment] 2020-10-24 17:06
The only reliable way for the server to know a song was played in the client is if the client notifies the server. That's what the `scrobble` call is used for. You can't rely on the time the song is downloaded from the server for two (maybe more) reasons:
1) Mobile clients usually do a "pre-cache", downloading the next few songs in advance to make playback smoother. So the server would mark those "future" songs as played even if you decided to stop the player and do something else. It would also create a situation where you could end up with songs in the "Recent Played" that were not played yet
2) If you use the client in offline mode, it will play songs already downloaded. In these case, you would miss these plays, as the server would never know about it. With the `scrobble` call, the client can queue the scrobbles to when you are back online (that what DSub does, for example)

Anyway, I'm closing this now, even though it is not perfect, it is working as intended. If you need scrobble support for a specific client, please create an issue in their repository (as I did for [Subplayer](https://github.com/peguerosdc/subplayer/issues/15))

**Closed by deluan** 2020-10-24 17:06 UTC

**Comment by SteveDinn** [comment] 2020-10-24 17:11
That is a great explanation. You have presented some situations that I had not considered. Please continue doing what you're doing :)

**Comment by deluan** [comment] 2020-10-28 17:30
Just an update: [Subplayer](https://github.com/peguerosdc/subplayer/) now implements the scrobble correctly. You should give it a try :)
