### ISSUE TITLE
UX : playlist column sizing

### ISSUE THREAD

**Issue by guim31** [deluan/navidrome#569] opened 2020-10-13 08:43 UTC
https://i.imgur.com/1FAoFd7.png

As shown above, the playlist display is messed up by the length of some song names, and by artist names (specific to classic music with LOTS of artist names displayed).
This is even worse on a small display like mine.

Would it be possible to either resize the columns / shorten the names like using `...` above x characters / even better : display the names on one single line which auto scrolls horizontally to show the full content of the cell ?

**Comment by deluan** [comment] 2020-10-13 14:13
This is not something easy to change, it is a behaviour implemented in the React-Admin framework (the foundation of Navidrome UI). Ideally I'd like to have resizable columns (with `...` as you suggested), but I don't think this can be implemented without a huge change in the lists support.

**Comment by deluan** [comment] 2020-11-03 15:22
This is a duplicate of https://github.com/deluan/navidrome/issues/240.

**Closed by deluan** 2020-11-03 15:22 UTC
Labels: help wanted, web ui
