### ISSUE TITLE
Skips tracks until last track and plays it

### ISSUE THREAD

**Issue by xsteadfastx** [deluan/navidrome#485] opened 2020-09-07 12:55 UTC
I sometimes run into the problem that navidrome doesnt play a album or track, skips all of them until it reaches the last track and plays. Here are the logs:

```
navidrome_1  | time="2020-09-07T12:51:07Z" level=info msg="Now Playing" artist=Daughter title=Mothers user=admin
navidrome_1  | time="2020-09-07T12:51:07Z" level=info msg="Streaming file" artist=Daughter bitRate=0 cached=false format=raw originalBitRate=320 originalFormat=mp3 title=Mothers transcoding=false user=admin
navidrome_1  | time="2020-09-07T12:51:07Z" level=info msg="Streaming file" artist=Daughter bitRate=0 cached=false format=raw originalBitRate=320 originalFormat=mp3 title=Mothers transcoding=false user=admin
navidrome_1  | time="2020-09-07T12:51:10Z" level=info msg="Streaming file" artist=Daughter bitRate=0 cached=false format=raw originalBitRate=320 originalFormat=mp3 title="Alone / With You" transcoding=false user=admin
navidrome_1  | time="2020-09-07T12:51:10Z" level=info msg="Now Playing" artist=Daughter title="Alone / With You" user=admin
navidrome_1  | time="2020-09-07T12:51:14Z" level=info msg="Streaming file" artist=Daughter bitRate=0 cached=false format=raw originalBitRate=320 originalFormat=mp3 title="No Care" transcoding=false user=admin
navidrome_1  | time="2020-09-07T12:51:14Z" level=info msg="Now Playing" artist=Daughter title="No Care" user=admin
navidrome_1  | time="2020-09-07T12:51:17Z" level=info msg="Streaming file" artist=Daughter bitRate=0 cached=false format=raw originalBitRate=320 originalFormat=mp3 title="To Belong" transcoding=false user=admin
navidrome_1  | time="2020-09-07T12:51:17Z" level=info msg="Now Playing" artist=Daughter title="To Belong" user=admin
navidrome_1  | time="2020-09-07T12:51:20Z" level=info msg="Streaming file" artist=Daughter bitRate=0 cached=false format=raw originalBitRate=320 originalFormat=mp3 title=Fossa transcoding=false user=admin
navidrome_1  | time="2020-09-07T12:51:20Z" level=info msg="Now Playing" artist=Daughter title=Fossa user=admin
navidrome_1  | time="2020-09-07T12:51:23Z" level=info msg="Streaming file" artist=Daughter bitRate=0 cached=false format=raw originalBitRate=320 originalFormat=mp3 title="Made of Stone" transcoding=false user=admin
navidrome_1  | time="2020-09-07T12:51:23Z" level=info msg="Now Playing" artist=Daughter title="Made of Stone" user=admin
navidrome_1  | time="2020-09-07T12:51:31Z" level=info msg="Streaming file" artist=Daughter bitRate=0 cached=false format=raw originalBitRate=320 originalFormat=mp3 title="Made of Stone" transcoding=false user=admin
navidrome_1  | time="2020-09-07T12:51:37Z" level=info msg="Now Playing" artist=Daughter title=How user=admin
navidrome_1  | time="2020-09-07T12:51:37Z" level=info msg="Streaming file" artist=Daughter bitRate=0 cached=false format=raw originalBitRate=320 originalFormat=mp3 title=How transcoding=false user=admin
navidrome_1  | time="2020-09-07T12:51:40Z" level=info msg="Streaming file" artist=Daughter bitRate=0 cached=false format=raw originalBitRate=320 originalFormat=mp3 title=Mothers transcoding=false user=admin
navidrome_1  | time="2020-09-07T12:51:41Z" level=info msg="Now Playing" artist=Daughter title=Mothers user=admin
navidrome_1  | time="2020-09-07T12:51:44Z" level=info msg="Streaming file" artist=Daughter bitRate=0 cached=false format=raw originalBitRate=320 originalFormat=mp3 title="Alone / With You" transcoding=false user=admin
navidrome_1  | time="2020-09-07T12:51:44Z" level=info msg="Now Playing" artist=Daughter title="Alone / With You" user=admin
navidrome_1  | time="2020-09-07T12:51:47Z" level=info msg="Streaming file" artist=Daughter bitRate=0 cached=false format=raw originalBitRate=320 originalFormat=mp3 title="No Care" transcoding=false user=admin
navidrome_1  | time="2020-09-07T12:51:47Z" level=info msg="Now Playing" artist=Daughter title="No Care" user=admin
navidrome_1  | time="2020-09-07T12:51:50Z" level=info msg="Streaming file" artist=Daughter bitRate=0 cached=false format=raw originalBitRate=320 originalFormat=mp3 title="To Belong" transcoding=false user=admin
navidrome_1  | time="2020-09-07T12:51:50Z" level=info msg="Now Playing" artist=Daughter title="To Belong" user=admin
navidrome_1  | time="2020-09-07T12:51:53Z" level=info msg="Streaming file" artist=Daughter bitRate=0 cached=false format=raw originalBitRate=320 originalFormat=mp3 title=Fossa transcoding=false user=admin
navidrome_1  | time="2020-09-07T12:51:53Z" level=info msg="Now Playing" artist=Daughter title=Fossa user=admin
navidrome_1  | time="2020-09-07T12:51:56Z" level=info msg="Streaming file" artist=Daughter bitRate=0 cached=false format=raw originalBitRate=320 originalFormat=mp3 title="Made of Stone" transcoding=false user=admin
navidrome_1  | time="2020-09-07T12:51:57Z" level=info msg="Now Playing" artist=Daughter title="Made of Stone" user=admin
```

**Comment by deluan** [comment] 2020-09-07 13:27
I've seen this behaviour before, seems that the React Player is time-outing while waiting for the stream to start. I'll do more investigation but if that is the case, it is an issue in the upstream React Player.

**Comment by deluan** [comment] 2020-09-07 20:46
May be related to #457

**Comment by deluan** [comment] 2020-09-09 01:21
Hey @xsteadfastx, what browser and OS (with versions) are you using?

**Comment by xsteadfastx** [comment] 2020-09-09 06:35
im using firefox 80.0 on a ubuntu bionic.

**Comment by skyzem** [comment] 2020-09-25 14:25
Hi, I had the same behavior with 0.33.0 but with 0.34.0 it disappeared.
Browser: Vivaldi 3.3.2022.45 (Stable channel) (64-bit) (chromium based)
OS: Win10
navidrome 0.34.0 on Debian 10.4

**Comment by deluan** [comment] 2020-09-25 14:31
Great @skyzem! I did some changes to the player configuration to fix a similar issue (#457) that may have fixed this as a collateral :)

Hey @xsteadfastx, can you confirm it is working in 0.34.0?

**Comment by xsteadfastx** [comment] 2020-09-28 06:43
i tested this over the weekend and so far no problems :+1: 

but how can a player change fixes this problem? i mean i had this also in dsub for example.

**Comment by deluan** [comment] 2020-09-28 12:40
As I said before, the issue was caused by the react player having a small timeout and skipping the track if the server takes too long to answer. But I never saw this happening on other players. I would assume it is a whole different issue.

Either way, I'm closing this now, but feel free to reopen if it happens again, or if you can reproduce the issue in other players.

**Closed by deluan** 2020-09-28 12:40 UTC
Labels: web ui
