### ISSUE TITLE
[WebUI] sorting isn't cleaned up for leading special characters

### ISSUE THREAD

**Issue by certuna** [deluan/navidrome#174] opened 2020-04-13 16:40 UTC
Sort within navidrome isn't cleaned up for special characters, so album/artist/song names with names like 
_(Get Ready) For The Power Of Disco_ or _...And Justice For All_ get sorted before A.

**Comment by deluan** [comment] 2020-04-13 16:45
This is related to adding sort fields to the DB (#121 and https://github.com/deluan/navidrome/issues/157#issuecomment-611709875)

**Comment by certuna** [comment] 2020-04-13 16:46
Yes, I assume this can be tackled either with Sort Artist, Sort Title, etc in the DB (as you say), or client-side cleanup (a bit messy).

**Comment by jvoisin** [comment] 2020-04-13 20:26
I would argue that it's working as intended: I'm happy to have `… and justice for all` either before the `a` or after the `z`.

**Comment by deluan** [comment] 2020-04-13 20:33
Me too. But I understand the asking, I had others asking for the same. I'll make this configurable

**Comment by jvoisin** [comment] 2020-04-13 20:36
Something like "list of articles to ignore: A, The, Les, El, …, (.+)"

**Comment by deluan** [comment] 2020-04-13 20:43
This list already exist: https://github.com/deluan/navidrome/blob/04eb4211869c8b319879a48bb442632d4c9267cb/conf/configuration.go#L27

 I could just allow it to contain symbols (and start using it for creating the sort fields, which I'm not doing at the moment). This is currently only used for generating the Artist Index in the Subsonic API

**Comment by certuna** [comment] 2020-04-14 13:56
Not a huge fan of this "ignore articles" because you cannot include articles from too many languages before you start getting false positives, like artists with a first name "Les". You'll also have to strip out things like L' De Een Det En al-, etc. I guess you'll have to decide how much of an English language focus you want navidrome to have by default.

Always a tough question: should "De La Soul" be sorted under D, L or S?

**Comment by deluan** [comment] 2020-04-14 14:01
Yeah, agree. But Navidrome only removes the "article" if it is a full word:
The Beatles => Beatles
Thelonious Monk => Thelonious Monk

These are more challenging though: L' De Een Det.... 

Answer for your question: "D" of course :)

**Comment by deluan** [comment] 2020-04-14 14:15
My general idea to handle this is:
1) If the track contains the "sort" fields, use them.
2) If not, generate one with the "remove articles" logic

This way you can always fix the sort tags if the articles logic fails you.
Thoughts?

**Comment by certuna** [comment] 2020-04-14 14:22
Yes, that's the most logical way to implement it I think.

**Comment by deluan** [comment] 2020-11-03 15:24
I think we can close this, it behaves as expected now. Feel free to reopen if you have any concerns.

**Closed by deluan** 2020-11-03 15:24 UTC
Labels: web ui
