### ISSUE TITLE
small ui issue

### ISSUE THREAD

**Issue by ericgaspar** [deluan/navidrome#452] opened 2020-08-19 20:57 UTC
With the small screen view, two small icons at the bottom do not have a green highlight on mouse over (play queue and shuffle). The icon on the left does not toggle between repeat, shuffle, etc.

![Capture d’écran 7](https://user-images.githubusercontent.com/46165813/90688748-2ea47b00-e26f-11ea-864b-e738296bcb75.png)

**Comment by deluan** [comment] 2020-08-19 21:23
Thanks for the report! I can't seem to reproduce the issue, it works for me on both my cellphone (Android) and my computer browser (Chrome). Check the attached video:

[Kapture 2020-08-19 at 17.14.01.mp4.zip](https://github.com/deluan/navidrome/files/5099375/Kapture.2020-08-19.at.17.14.01.mp4.zip) 

Maybe I didn't understand what the issue is?

**Comment by ericgaspar** [comment] 2020-08-19 21:54
It works on my cellphone (iPhone), but not on my computers browser: Safarie Chromium or Firefox 🤔
[Enregistrement de l’écran.mov.zip](https://github.com/deluan/navidrome/files/5099522/Enregistrement.de.l.ecran.mov.zip)

**Comment by deluan** [comment] 2020-08-19 22:09
Ok, I was able to reproduce it. It is a bug in the upstream react-player. You can check their demo site: https://www.lijinke.cn/react-music-player/

I'll open an issue there, and link it to this one

**Comment by deluan** [comment] 2020-09-06 16:34
Fixed in 900337081bc94698307e0b555fc99c1c09d7d760

**Closed by deluan** 2020-09-06 16:34 UTC
Labels: blocked, bug
