### ISSUE TITLE
WebUI shows artists without capital letters on the last page

### ISSUE THREAD

**Issue by r0arkin** [deluan/navidrome#157] opened 2020-04-09 19:19 UTC
The webUI shows artists that don't have capital letters on the last page. Is this intentional or would this need to be fixed?
<img width="1420" alt="Screen Shot 2020-04-09 at 12 16 08 PM" src="https://user-images.githubusercontent.com/46236585/78932350-2b48e980-7a5c-11ea-85d9-1f039f9546da.png">

**Comment by deluan** [comment] 2020-04-09 19:23
Thanks for reminding me about this. This needs to be fixed! Also `The Beatles` should be sorted as `Beatles`. This will involve introducing SortArtists/SortAlbums, maybe related to #121

**Comment by r0arkin** [comment] 2020-04-09 19:31
Awesome! Thanks for everything you do. I flip between Navi and Airsonic on play:sub. I really like how lightweight and fast Navi is, just missing some stuff before I can flip over for good! :)

**Comment by certuna** [comment] 2020-04-13 16:42
I noticed this is also with library scanning, folders scan A-Z, and then a-z.

**Comment by deluan** [comment] 2020-04-24 18:35
> I noticed this is also with library scanning, folders scan A-Z, and then a-z.

Not related, the scanning order should not affect the imported data in the DB. This is caused by the way the Filesystem returns lists of children (files/directories) in a given folder

**Comment by deluan** [comment] 2020-04-24 19:07
Fixed in #208

**Closed by deluan** 2020-04-24 19:07 UTC
Labels: bug, web ui
